### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by githappens** [johnBuffer/VerletSFML#3]
Hi Jean,

Great work, I have found your video on the Verlet magic quite educational! I was wondering what sort of license did you think of for this piece of code. Have you considered what license to use for this specific repo?
If you went with something permissive I'd like to use this as a starting point for a project.
Thanks

**Comment by johnBuffer** [comment]
Hi,
I just updated the repo with the MIT license which should allow you to do whatever you want with the code :)

**Comment by githappens** [comment]
Super, thank you for that and for the blazing swift response. :)
